### PR TITLE
Capstone Project

### PR DESCRIPTION
**Pull request by CarlosIgreda**
## Capstone: Conference Page

For this milestone I:

✅ Used GitHub Flow
✅ Used linters
✅ Used basic JavaScript syntax
✅ Used JavaScript to manipulate DOM elements
✅ Used JavaScript events
✅ Used objects to store and access data
✅ Used media queries
✅ Created a mobile menu for interaction
✅ Designed 2 pages (home and about)
✅ Documented my work in a professional way
✅ Added my loom video

### CODE REVIEW

**Review by ABDULALI3468 — COMMENTED** [review]
Hi @CarlosIgreda , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

> You have submitted a project, in which Linters are not showing up. Please consider reviewing it as its necessary to catch any bugs or anything else to make your code base look more professional. 💯 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by CarlosIgreda** [comment]
Hi @ABDULALI3468. Could I ask you for some help with it? this is my whatsapp number +51921459466, I don't know how to solve this linters issue.

**Comment by CarlosIgreda** [comment]
Done @ABDULALI3468, I solved the linters issue, I had to redo all linters config to have everything okay, now it is working properly.

**Review by KayLemba — APPROVED** [review]
[[# STATUS: APPROVED :green_circle: :clap: 

Hello @CarlosIgreda     , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉  Keep up the good work 🥂 

HIGHLIGHTS:

- [x]  Your repo is professional  😎 
- [x] Descriptive P.R 💯 
- [x] linters are passing
- [x] Professional README 💯 
- [x] Your work is well documented
- [x] Good implementation of JavaScript
- [x] Nice and Neat UI design
 










 








Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 



well-1

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._]]

**Comment by CarlosIgreda** [comment]
Thanks a lot for your feedback and support @KayLemba !! I really appreciate it 🤓

**Comment by KayLemba** [comment]
You are welcome @CarlosIgreda

**Pull request merged**
